### 1. What's the version of Pandas that you installed?

In [79]:
import pandas as pd
import os
import numpy as np
pd.__version__

'1.4.4'

In [80]:
if not os.path.isfile("housing.csv"): 
    !wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv housing.csv

In [81]:
housing_df = pd.read_csv('housing.csv')

### 2. How many columns are in the dataset?

In [82]:
housing_df.shape[1]

10

### 3. Which columns in the dataset have missing values?

In [83]:
housing_df.isnull().sum()[housing_df.isnull().sum() > 0]

total_bedrooms    207
dtype: int64

### 4. How many unique values does the ocean_proximity column have?

In [84]:
housing_df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [85]:
housing_df.ocean_proximity.nunique()

5

### 5. What's the average value of the median_house_value for the houses located near the bay?

In [86]:
houses_is_near_bay = housing_df['ocean_proximity'] == "NEAR BAY" 
houses_near_bay = housing_df[houses_is_near_bay]
houses_near_bay.median_house_value.mean()

259212.31179039303

### Question 6
1. Calculate the average of total_bedrooms column in the dataset.
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3. Now, calculate the average of total_bedrooms again.
4. Has it changed?

In [87]:
avg_total_bedrooms = housing_df.total_bedrooms.mean()
print(avg_total_bedrooms)
housing_df["total_bedrooms"] = housing_df.total_bedrooms.fillna(avg_total_bedrooms)
new_avg_total_bedrooms = housing_df.total_bedrooms.mean()
print(new_avg_total_bedrooms)

537.8705525375618
537.8705525375639


#### No it has not changed using 3 decimal places

### Question 7
1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

In [88]:
island_houses = housing_df[housing_df.ocean_proximity == "ISLAND"]
island_houses.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [89]:
X = island_houses[['housing_median_age', 'total_rooms', 'total_bedrooms']].values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [90]:
XTX = X.T.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [91]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [92]:
XTX_inv_XT = XTX_inv.dot(X.T)

In [93]:
y =  [950, 1300, 800, 1000, 1300]

In [94]:
XTX_inv_XT.dot(y)

array([23.12330961, -1.48124183,  5.69922946])